version: "3.3"

services:
  api:
    image: horizontalorg/tellaweb-api
    volumes:
       - ./data:/usr/src/app/data
       - ./db:/usr/src/app/db    
    restart: unless-stopped
    networks: 
        - "net"
    environment:
      PORT: 3001
      VIRTUAL_PORT: 3001
      VIRTUAL_HOST: ${API_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${API_VIRTUAL_HOST}
      JWT_SECRET: ${JWT_SECRET}  
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      PUBLIC_DOMAIN:  ${PUBLIC_DOMAIN}
    expose:
      - "3001"

  app:
    image: horizontalorg/tellaweb-admin
    restart: unless-stopped
    networks:
        - "net"
    expose:
      - "3000"
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      NEXT_PUBLIC_MAPBOX_TOKEN:  ${NEXT_PUBLIC_MAPBOX_TOKEN}

  nginx:
    image: "jwilder/nginx-proxy:latest"
    container_name: "nginx"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "htpasswd:/srv/docker/nginx/htpasswd/"
        - "./nginx-config/proxy_custom_config.conf:/etc/nginx/conf.d/proxy_custom_config.conf:ro"
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - "net"
    ports:
        - "80:80"
        - "443:443"
        
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    container_name: "letsencrypt-helper"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
        NGINX_PROXY_CONTAINER: "nginx"
        DEFAULT_EMAIL: "user@domain.com"
    restart: "always"
    depends_on:
        - "nginx"
    networks: 
        - "net"

volumes:
  certs:
  html:
  vhost:
  dhparam:
  htpasswd:

networks:
  net:
    external: true
