version: "3.3"

services:
  api:
    image: tellaweb-api-prod  
    volumes:
       - ./data:/usr/src/app/data
       - ./db:/usr/src/app/db
    build:
      context: https://github.com/Horizontal-org/tellaweb-nestjs.git#main
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      PORT: 3001
      JWT_SECRET: secret  
      COOKIE_DOMAIN: http://app:3000
    expose:
      - "3001"

  app:
    image: tellaweb-tapp-prod
    build:
      context: https://github.com/Horizontal-org/tellaweb-frontend.git#main
      dockerfile: ./Dockerfile
      args:
        api_url: "http://api:3001"
    restart: unless-stopped
    ports:
      - 3000:3000      
    expose:
      - "3000"
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: beta.web.tella-app.org

  nginx:
    image: "jwilder/nginx-proxy:latest"
    container_name: "nginx"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "htpasswd:/srv/docker/nginx/htpasswd/"
        - "./nginx-config/proxy_custom_config.conf:/etc/nginx/conf.d/proxy_custom_config.conf:ro"
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - "net"
    ports:
        - "80:80"
        - "443:443"

volumes:
  certs:
  html:
  vhost:
  dhparam:
  htpasswd:

networks:
  net:
    external: true